GO
/****** Object:  Database DevProjMainDB    Script Date: 18/07/2021 12:18:05 PM ******/
CREATE DATABASE DevProjMainDB
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DevProjMainDB', FILENAME = N'C:\Users\thwin\DevProjMainDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DevProjMainDB_log', FILENAME = N'C:\Users\thwin\DevProjMainDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE DevProjMainDB SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC DevProjMainDB.[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE DevProjMainDB SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE DevProjMainDB SET ANSI_NULLS OFF 
GO
ALTER DATABASE DevProjMainDB SET ANSI_PADDING OFF 
GO
ALTER DATABASE DevProjMainDB SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE DevProjMainDB SET ARITHABORT OFF 
GO
ALTER DATABASE DevProjMainDB SET AUTO_CLOSE ON 
GO
ALTER DATABASE DevProjMainDB SET AUTO_SHRINK OFF 
GO
ALTER DATABASE DevProjMainDB SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE DevProjMainDB SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE DevProjMainDB SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE DevProjMainDB SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE DevProjMainDB SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE DevProjMainDB SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE DevProjMainDB SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE DevProjMainDB SET  ENABLE_BROKER 
GO
ALTER DATABASE DevProjMainDB SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE DevProjMainDB SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE DevProjMainDB SET TRUSTWORTHY OFF 
GO
ALTER DATABASE DevProjMainDB SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE DevProjMainDB SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE DevProjMainDB SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE DevProjMainDB SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE DevProjMainDB SET RECOVERY SIMPLE 
GO
ALTER DATABASE DevProjMainDB SET  MULTI_USER 
GO
ALTER DATABASE DevProjMainDB SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE DevProjMainDB SET DB_CHAINING OFF 
GO
ALTER DATABASE DevProjMainDB SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE DevProjMainDB SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE DevProjMainDB SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE DevProjMainDB SET QUERY_STORE = OFF
GO
USE DevProjMainDB
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE DevProjMainDB
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 18/07/2021 12:18:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OccupationRating]    Script Date: 18/07/2021 12:18:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OccupationRating](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Occupation] [nvarchar](max) NULL,
	[Rating] [nvarchar](max) NULL,
 CONSTRAINT [PK_OccupationRating] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 18/07/2021 10:30:55 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Customer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](max) NULL,
	[Age] [decimal](18, 2) NULL,
	[DateOfBirth] [datetime] NULL,
	[Occupation] [varchar](1000) NULL,
	[SumInsured] [decimal](18, 2) NULL,
	[MonthlyExpensesTotal] [decimal](18, 2) NULL,
	[State] [varchar](100) NULL,
	[Postcode] [int] NULL	
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RatingFactor]    Script Date: 18/07/2021 12:18:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RatingFactor](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Rating] [varchar](500) NULL,
	[Factor] [decimal](18, 2) NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE DevProjMainDB SET  READ_WRITE 
GO
